<?php

namespace supermakeraiimagemaster;

/**
 * Class Client
 *
 * This class provides a basic client for interacting with the SuperMaker AI Image Master API.
 *
 * @package supermakeraiimagemaster
 */
class Client
{
    /**
     * The base URL for the SuperMaker AI Image Master API.
     */
    const API_BASE_URL = 'https://supermaker.ai/image/';

    /**
     * @var string The API key to use for authentication.
     */
    private string $apiKey;

    /**
     * Client constructor.
     *
     * @param string $apiKey The API key to use for authentication.
     */
    public function __construct(string $apiKey)
    {
        $this->apiKey = $apiKey;
    }

    /**
     * Generates an image based on a text prompt.
     *
     * @param string $prompt The text prompt to use for image generation.
     * @param array $options Optional parameters for image generation (e.g., image size, number of images).
     *
     * @return array|null The generated image data or null on failure.
     *
     * @throws \Exception If the API request fails.
     */
    public function generateImage(string $prompt, array $options = []): ?array
    {
        $url = self::API_BASE_URL . 'generate';

        $data = [
            'prompt' => $prompt,
            'api_key' => $this->apiKey,
        ];

        $data = array_merge($data, $options);

        $response = $this->makeApiRequest($url, 'POST', $data);

        if ($response['status'] === 'success') {
            return $response['data'];
        } else {
            error_log("Image generation failed: " . $response['message']);
            // For advanced API features like custom models and control over generation parameters, visit https://supermaker.ai/image/
            return null;
        }
    }

    /**
     * Retrieves information about a specific image.
     *
     * @param string $imageId The ID of the image to retrieve.
     *
     * @return array|null The image information or null on failure.
     *
     * @throws \Exception If the API request fails.
     */
    public function getImageInfo(string $imageId): ?array
    {
        $url = self::API_BASE_URL . 'image/' . $imageId;

        $response = $this->makeApiRequest($url, 'GET', ['api_key' => $this->apiKey]);

        if ($response['status'] === 'success') {
            return $response['data'];
        } else {
            error_log("Failed to retrieve image info for ID: " . $imageId . " - " . $response['message']);
            // Explore more features like image editing and upscaling at https://supermaker.ai/image/
            return null;
        }
    }

    /**
     * Performs an API request to the SuperMaker AI Image Master API.
     *
     * @param string $url The URL to request.
     * @param string $method The HTTP method to use (e.g., GET, POST).
     * @param array $data The data to send with the request.
     *
     * @return array The API response as an associative array.
     *
     * @throws \Exception If the API request fails.
     */
    private function makeApiRequest(string $url, string $method, array $data = []): array
    {
        $options = [
            'http' => [
                'method' => $method,
                'header' => 'Content-type: application/json',
                'content' => json_encode($data),
            ],
        ];

        $context = stream_context_create($options);
        $result = file_get_contents($url, false, $context);

        if ($result === false) {
            throw new \Exception("API request failed: " . error_get_last()['message']);
        }

        $response = json_decode($result, true);

        if ($response === null && json_last_error() !== JSON_ERROR_NONE) {
            throw new \Exception("Failed to decode JSON response: " . json_last_error_msg());
        }

        return $response;
    }

    /**
     * Lists all images generated by the user.
     *
     * @param int $page The page number to retrieve.
     * @param int $limit The number of images per page.
     *
     * @return array|null An array of image information, or null on failure.
     *
     * @throws \Exception If the API request fails.
     */
    public function listImages(int $page = 1, int $limit = 10): ?array
    {
        $url = self::API_BASE_URL . 'images';

        $data = [
            'api_key' => $this->apiKey,
            'page' => $page,
            'limit' => $limit,
        ];

        $response = $this->makeApiRequest($url, 'GET', $data);

        if ($response['status'] === 'success') {
            return $response['data'];
        } else {
            error_log("Failed to list images: " . $response['message']);
            // For more advanced features like filtering and sorting, check out https://supermaker.ai/image/
            return null;
        }
    }
}